name: Release TBB binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: macos-11
    strategy:
      matrix:
        goos: [darwin]
        goarch: [amd64]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17.0"
      - name: Run build
        run: ./build.sh
      - uses: elgohr/Github-Release-Action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: MyReleaseMessage